# Load data for data folder

In [10]:
import pandas as pd
import numpy as np


df = pd.read_csv("../data/RAA04_Estimates_of_Household_Income.csv")

# Show unique Statistic Label values

In [4]:

df["Statistic Label"].unique()

array(["Compensation of Employees (i.e. Wages and Salaries, Benefits in kind, Employers' social insurance contribution)",
       'Rent of dwellings (including imputed rent of owner-occupied dwellings)',
       'Total Household Income', 'Total Income per Person',
       'Index of Total Income per Person', 'Current Taxes on Income',
       'Disposable Household Income', 'Disposable Income per Person',
       'Index of Disposable Income per Person',
       'Disposable Income per Person (excluding Rent)',
       'Index of Disposable Income per Person (excluding Rent)'],
      dtype=object)

# Statistic Label to horizontal attributes

In [ ]:

df = pd.read_csv("../data/RAA04_Estimates_of_Household_Income.csv")


# Pivot: Statistic Label to horizontal attributes
wide_df = df.pivot_table(
    index=["Year", "NUTS 2 Region", "UNIT"],   # keep these vertical
    columns="Statistic Label",                 # turn into horizontal columns
    values="VALUE",                            # fill with numeric values
    aggfunc="first"
)

# Reset index to make it a flat table
wide_df = wide_df.reset_index()

# Save
wide_df.to_csv("../data/RAA04_wide_format.csv", index=False)

# Smaller data size ： Merge Rows: One Row per Year + Region

In [13]:
# Load the existing wide-format dataset
df = pd.read_csv("../data/RAA04_wide_format.csv")

# Metadata columns (these should NOT be merged across rows)
meta = ["Year", "NUTS 2 Region", "UNIT"]

# Value columns (all columns that are actual data and need merging)
value_cols = [c for c in df.columns if c not in meta]

print("Value columns detected:")
value_cols

Value columns detected:

["Compensation of Employees (i.e. Wages and Salaries, Benefits in kind, Employers' social insurance contribution)",
 'Current Taxes on Income',
 'Disposable Household Income',
 'Disposable Income per Person',
 'Disposable Income per Person (excluding Rent)',
 'Index of Disposable Income per Person',
 'Index of Disposable Income per Person (excluding Rent)',
 'Index of Total Income per Person',
 'Rent of dwellings (including imputed rent of owner-occupied dwellings)',
 'Total Household Income',
 'Total Income per Person']

In [14]:
# Mapping for UNIT suffix
def unit_suffix(u):
    if "Million" in u:
        return "(Million)"
    elif "State" in u or "100" in u:
        return "(State100)"
    else:
        return "(Euro)"   # Default unit suffix

In [15]:
# Group data by Year + Region (each group contains 3 UNIT rows)
grouped = df.groupby(["Year", "NUTS 2 Region"])

final_rows = []

for (year, region), group in grouped:
    # Start building the merged single row
    row = {"Year": year, "NUTS 2 Region": region}
    
    # For each economic indicator column
    for col in value_cols:
        
        # Find the row where this column has a non-null value
        non_null_rows = group[group[col].notna()]
        
        # If no data at all for this column, skip it
        if len(non_null_rows) == 0:
            continue
        
        # Extract the actual value
        val = non_null_rows.iloc[0][col]
        
        # Identify which UNIT this value came from
        unit = non_null_rows.iloc[0]["UNIT"]
        
        # Rename column with unit suffix for clarity
        new_col = col + " " + unit_suffix(unit)
        
        # Store into row dictionary
        row[new_col] = val
    
    final_rows.append(row)

In [16]:
# Convert merged rows into DataFrame
final = pd.DataFrame(final_rows)

# Save final result
final.to_csv("../data/RAA04_final_one_row_with_rename.csv", index=False)

final.head()

,Year,NUTS 2 Region,"Compensation of Employees (i.e. Wages and Salaries, Benefits in kind, Employers' social insurance contribution) (Million)",Current Taxes on Income (Million),Disposable Household Income (Million),Disposable Income per Person (Euro),Disposable Income per Person (excluding Rent) (Euro),Index of Disposable Income per Person (State100),Index of Disposable Income per Person (excluding Rent) (State100),Index of Total Income per Person (State100),Rent of dwellings (including imputed rent of owner-occupied dwellings) (Million),Total Household Income (Million),Total Income per Person (Euro)
0,2000,Eastern & Midland,23144.07,11861.73,23233.55,12873.23,11863.41,102.58,48.05,110.73,1822.52,35095.28,19445.58
1,2000,Ireland,42023.36,19066.96,47739.92,12549.09,11713.17,100.00,100.00,100.00,3180.03,66806.88,17561.10
2,2000,Northern & Western,5945.04,2240.21,7965.59,11533.87,10874.85,91.91,16.85,84.15,455.13,10205.80,14777.61
3,2000,Southern,12934.25,4965.02,16540.78,12637.81,11948.36,100.71,35.10,93.57,902.38,21505.80,16431.28
4,2001,Eastern & Midland,25819.84,12795.37,26760.07,14592.59,13382.46,102.73,48.09,110.69,2219.14,39555.44,21570.05

# Filier for target year range

In [20]:
df = pd.read_csv("../data/RAA04_final_one_row_with_rename.csv")
df = df[(df["Year"] >= 2014) & (df["Year"] <= 2023)]
df.to_csv("../data/RAA04_final_2014_2023.csv", index=False)
df.head(40)

,Year,NUTS 2 Region,"Compensation of Employees (i.e. Wages and Salaries, Benefits in kind, Employers' social insurance contribution) (Million)",Current Taxes on Income (Million),Disposable Household Income (Million),Disposable Income per Person (Euro),Disposable Income per Person (excluding Rent) (Euro),Index of Disposable Income per Person (State100),Index of Disposable Income per Person (excluding Rent) (State100),Index of Total Income per Person (State100),Rent of dwellings (including imputed rent of owner-occupied dwellings) (Million),Total Household Income (Million),Total Income per Person (Euro)
56,2014,Eastern & Midland,41611.18,23636.15,40361.61,18015.50,16413.23,98.72,46.91,106.99,3589.69,63997.76,28565.55
57,2014,Ireland,76019.28,39320.23,84899.19,18248.23,16848.99,100.00,100.00,100.00,6509.95,124219.42,26699.73
58,2014,Northern & Western,11090.48,4886.56,14850.63,17490.51,16345.64,95.85,17.70,87.06,972.07,19737.19,23245.72
59,2014,Southern,23317.62,10797.52,29686.95,18993.45,17747.02,104.08,35.39,97.01,1948.18,40484.47,25901.60
60,2015,Eastern & Midland,44490.29,25006.63,43140.00,19078.03,17298.34,99.58,47.32,107.70,4024.31,68146.63,30136.85
61,2015,Ireland,80874.94,41439.60,89960.96,19157.86,17603.23,100.00,100.00,100.00,7300.20,131400.56,27982.73
62,2015,Northern & Western,11689.94,5135.14,15545.97,18140.57,16867.53,94.69,17.49,86.24,1090.96,20681.11,24132.76
63,2015,Southern,24694.72,11297.83,31275.00,19824.90,18439.90,103.48,35.19,96.44,2184.93,42572.83,26986.48
64,2016,Eastern & Midland,47593.13,25523.50,46127.43,20155.84,18219.24,101.31,47.92,108.68,4431.98,71650.93,31308.59
65,2016,Ireland,86257.55,42360.93,94553.66,19895.71,18309.99,100.00,100.00,100.00,7536.10,136914.59,28809.18
66,2016,Northern & Western,12437.27,5301.59,15976.41,18420.47,17266.91,92.59,17.21,85.16,1000.51,21278.00,24533.09
67,2016,Southern,26227.15,11535.84,32449.82,20324.24,19006.69,102.15,34.87,95.63,2103.61,43985.65,27549.46
68,2017,Eastern & Midland,51060.68,27259.01,49308.34,21239.11,19161.28,101.55,48.02,108.88,4823.86,76567.34,32980.67
69,2017,Ireland,92268.18,45199.51,100829.10,20914.20,19215.48,100.00,100.00,100.00,8189.70,146028.61,30289.59
70,2017,Northern & Western,13237.80,5638.88,16881.98,19187.53,17954.33,91.74,17.05,84.51,1085.02,22520.86,25596.50
71,2017,Southern,27969.71,12301.62,34638.79,21386.47,19978.26,102.26,34.93,95.68,2280.82,46940.41,28981.66
72,2018,Eastern & Midland,54529.03,28745.70,51998.03,22080.17,19814.13,102.79,48.60,109.64,5336.43,80743.72,34286.59
73,2018,Ireland,98206.56,47885.88,105047.79,21480.38,19631.02,100.00,100.00,100.00,9044.10,152933.68,31272.18
74,2018,Northern & Western,14026.49,5994.40,17571.30,19687.90,18347.68,91.66,17.06,84.43,1196.13,23565.71,26404.37
75,2018,Southern,29651.04,13145.78,35478.46,21594.38,20065.71,100.53,34.34,94.64,2511.53,48624.24,29595.71
76,2019,Eastern & Midland,59232.90,30661.75,56575.51,23306.14,20817.83,102.60,49.24,108.97,6040.38,87237.26,35937.18
77,2019,Ireland,106113.02,50976.97,112840.00,22715.83,20658.49,100.00,100.00,100.00,10219.77,163816.97,32978.01
78,2019,Northern & Western,15082.83,6344.49,18660.02,21105.08,19578.94,92.91,16.87,85.76,1349.34,25004.51,28280.91
79,2019,Southern,31797.29,13970.73,37604.48,22710.48,21001.32,99.98,33.89,94.45,2830.06,51575.21,31147.83
80,2020,Eastern & Midland,59030.56,29834.00,59517.09,24191.78,21634.11,102.30,49.09,108.16,6292.44,89351.09,36318.34
81,2020,Ireland,105800.86,50002.31,119053.26,23647.81,21536.47,100.00,100.00,100.00,10629.43,169055.58,33579.88
82,2020,Northern & Western,15015.85,6254.01,20119.16,22452.73,20889.24,94.95,17.26,87.65,1401.00,26373.17,29432.13
83,2020,Southern,31754.44,13914.30,39417.01,23488.46,21738.91,99.33,33.65,94.64,2936.00,53331.32,31779.95
84,2021,Eastern & Midland,65494.70,35274.24,63396.11,25421.39,22453.75,103.58,49.23,109.41,7400.75,98670.35,39566.12
85,2021,Ireland,116964.17,59167.37,124967.20,24542.60,22338.71,100.00,100.00,100.00,11221.86,184134.57,36162.62
86,2021,Northern & Western,16573.98,7535.73,20427.84,22607.45,21217.18,92.12,16.85,85.58,1256.23,27963.57,30947.23
87,2021,Southern,34895.48,16357.39,41143.25,24281.19,22767.49,98.93,33.92,93.84,2564.89,57500.65,33934.70
88,2022,Eastern & Midland,72295.21,38710.68,68758.63,26803.62,23613.29,103.19,49.45,109.07,8184.09,107469.32,41893.90
89,2022,Ireland,128197.82,64652.15,135065.68,25975.44,23559.00,100.00,100.00,100.00,12564.86,199717.83,38409.15
90,2022,Northern & Western,17969.52,8282.61,21820.73,23865.06,22275.98,91.88,16.63,85.72,1452.95,30103.34,32923.65
91,2022,Southern,37933.08,17658.85,44486.32,25862.12,24160.03,99.56,33.93,94.06,2927.82,62145.18,36128.09
92,2023,Eastern & Midland,79716.36,41480.62,76850.45,29201.61,25328.38,102.93,49.57,108.80,10193.25,118331.07,44963.40
93,2023,Ireland,141941.44,68621.27,150245.90,28370.41,25389.45,100.00,100.00,100.00,15786.78,218867.17,41327.93
94,2023,Northern & Western,20040.13,8642.66,24225.73,26256.02,24220.55,92.55,16.62,86.20,1878.07,32868.39,35623.00
95,2023,Southern,42184.95,18497.99,49169.72,28234.57,26101.05,99.52,33.81,94.02,3715.46,67667.71,38856.60